/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GCcalculator;

import java.awt.Color;
import java.awt.Graphics;
import java.text.DecimalFormat;
import javax.swing.JOptionPane;
/**
 * Er is een GUI gebouwd om in beeld te krijgen wat de GC percentage is van een sequentie dat in de GUI wordt geopend. 
 * De GC percentage wordt in een balk weergegeven in procenten. 
 * @author Pinar Kubra Kumurcu
 */
public class GUI extends javax.swing.JFrame {

    public String input;
    public String output;
    private String TotaalLengte;
    /**
     * Creates new form GUI
     */
    public GUI() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        KoptekstLabel = new javax.swing.JLabel();
        BestandLabel = new javax.swing.JLabel();
        BestandVeld = new javax.swing.JTextField();
        BestandsNaamLabel = new javax.swing.JLabel();
        BestandsNaamTekstLabel = new javax.swing.JLabel();
        InformatieLabel = new javax.swing.JLabel();
        BladerButton = new javax.swing.JButton();
        OpenButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        GegevensArea = new javax.swing.JTextArea();
        BerekenButton = new javax.swing.JButton();
        AchtergrondPanel = new javax.swing.JPanel();
        HeaderLabel = new javax.swing.JLabel();
        Label0 = new javax.swing.JLabel();
        Label100 = new javax.swing.JLabel();
        BeginLabel = new javax.swing.JLabel();
        TotLabel = new javax.swing.JLabel();
        BeginVeld = new javax.swing.JTextField();
        EindVeld = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("GCcalculator- Pinar Kumurcu");

        KoptekstLabel.setText("Geef een bestand om te visualiseren:");

        BestandLabel.setText("Bestand");

        BestandVeld.setForeground(new java.awt.Color(204, 204, 255));
        BestandVeld.setText("Klik op Blader");
        BestandVeld.setToolTipText("");

        BestandsNaamLabel.setText("Bestandsnaam");

        BestandsNaamTekstLabel.setText("Kies bestand");

        InformatieLabel.setText("Informatie");

        BladerButton.setText("Blader");
        BladerButton.setToolTipText("Bladeren");
        BladerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BladerButtonActionPerformed(evt);
            }
        });

        OpenButton.setText("Open");
        OpenButton.setToolTipText("Openen");
        OpenButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OpenButtonActionPerformed(evt);
            }
        });

        GegevensArea.setColumns(20);
        GegevensArea.setRows(5);
        jScrollPane1.setViewportView(GegevensArea);

        BerekenButton.setText("Bereken GC%");
        BerekenButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BerekenButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout AchtergrondPanelLayout = new javax.swing.GroupLayout(AchtergrondPanel);
        AchtergrondPanel.setLayout(AchtergrondPanelLayout);
        AchtergrondPanelLayout.setHorizontalGroup(
            AchtergrondPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 496, Short.MAX_VALUE)
        );
        AchtergrondPanelLayout.setVerticalGroup(
            AchtergrondPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 77, Short.MAX_VALUE)
        );

        HeaderLabel.setText("header");

        Label0.setText("0%");

        Label100.setText("100%");

        BeginLabel.setText("Begin");

        TotLabel.setText("Tot");

        BeginVeld.setText("1");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(254, 254, 254)
                        .addComponent(KoptekstLabel))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(BestandsNaamLabel)
                                .addGap(18, 18, 18)
                                .addComponent(BestandsNaamTekstLabel))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(InformatieLabel)
                                .addGap(40, 40, 40)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                            .addComponent(Label0)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(Label100))
                                        .addComponent(AchtergrondPanel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addGroup(layout.createSequentialGroup()
                                                    .addComponent(BestandLabel)
                                                    .addGap(49, 49, 49)
                                                    .addComponent(BestandVeld, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addComponent(jScrollPane1))
                                            .addComponent(HeaderLabel))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(BerekenButton)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(BladerButton)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(OpenButton))
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(TotLabel)
                                                    .addComponent(BeginLabel))
                                                .addGap(18, 18, 18)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(EindVeld)
                                                    .addComponent(BeginVeld))))))))))
                .addContainerGap(32, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(KoptekstLabel)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BestandLabel)
                    .addComponent(BestandVeld, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BladerButton)
                    .addComponent(OpenButton))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BestandsNaamLabel)
                    .addComponent(BestandsNaamTekstLabel)
                    .addComponent(BeginLabel)
                    .addComponent(BeginVeld, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(InformatieLabel)
                            .addComponent(HeaderLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(TotLabel)
                            .addComponent(EindVeld, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(69, 69, 69)
                        .addComponent(BerekenButton)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Label0)
                    .addComponent(Label100))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(AchtergrondPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(130, 130, 130))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
 * ActionPerformed voor het zoeken naar het bestand.
 */
    private void BladerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BladerButtonActionPerformed
        // TODO add your handling code here:
        FileChooser f1 = new FileChooser();
        FileChooser.Chooser();

        BestandVeld.setText(f1.getPath());
        BestandsNaamTekstLabel.setText(f1.getFileName());
    }//GEN-LAST:event_BladerButtonActionPerformed
/**
 * ActionPerformed voor het openen van het bestand
 */
    private void OpenButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OpenButtonActionPerformed
        // TODO add your handling code here:
        FileReader reader1 = new FileReader();
        String pad;
        pad = BestandVeld.getText();

        GegevensArea.setText(reader1.FileReader(pad));
        
        HeaderLabel.setText("Naam Gen+ Accessie Code " +reader1.getHeader());
        //EindVeld.setText(TotaalLengte);

    }//GEN-LAST:event_OpenButtonActionPerformed

/**
 * ActionPerformed voor het berekenen van de GC percentage van de sequentie.
 */
    private void BerekenButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BerekenButtonActionPerformed
        // TODO add your handling code here:
  
        if (evt.getSource() == BerekenButton) {
            String seq = GegevensArea.getText().toUpperCase();
            
        try{    
            int count = 0;
            for (int i = 0; i < seq.length(); i++) {
                char x = seq.charAt(i);
                count = count+1;
            }   
            
            int A = Berekening.A(seq);
            int G = Berekening.G(seq);           
            int T = Berekening.T(seq);
            int C = Berekening.C(seq);
            int TotaalLengte = (A+T+G+C);
            //int TotaalLengte = (Berekening.A(seq)+ Berekening.G(seq)+ Berekening.T(seq)+ Berekening.C(seq));
            System.out.println("Het totaal aantal nucleotiden in dit bestand zijn: "+ TotaalLengte + " nucleotiden.");
            

            // Het aantal percentages berekenen van deze nucleotiden. 
            double PerGC = (G+C)*100/count; //Hier wordt het percentage van de GC berekend. Het aantal G en C's worden bij elkaar opgeteld, *100 gedaan en gedaan door het totaal aantal.
//            DecimalFormat formatter = new DecimalFormat("##.##");
//            AchtergrondPanel.setText(formatter.format(PerGC));

//            int PerA = A*100/count;
//            int PerG = G*100/count;
//            int PerT = T*100/count;
//            int PerC = C*100/count;



            
            
            Graphics paper = AchtergrondPanel.getGraphics();// de gegevens worden weergegevens in de panel AchtergrondPanel.        
            // De weergave van nucleotide G en C (GC) in percentages
            paper.setColor(Color.DARK_GRAY);
            paper.fillRect(0, 0, (int) (PerGC*4), 50);
            paper.setColor(Color.black);
            paper.drawString("GC% van deze sequentie is "+PerGC+"%", (int) Math.round(PerGC*3.25f),25);
            System.out.println("GC percentage van deze sequentie is "+PerGC + "%");
            
        int i = TotaalLengte;
        EindVeld.setText(Integer.toString(i)); // Hier wordt de EindPositie weergegeven in het tekstveld. 
                      
        }
        
        catch (NotANucl err) {
            System.out.println("Dit is geen DNA sequentie");
            JOptionPane.showMessageDialog(null, "Het bestand bevat meer dan alleen DNA", "Error Message", JOptionPane.ERROR_MESSAGE);
        }
            
        }
  
    }                                           


    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GCcalculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GCcalculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GCcalculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GCcalculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUI().setVisible(true);
            }
        });
    }//GEN-LAST:event_BerekenButtonActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new GUI().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel AchtergrondPanel;
    private javax.swing.JLabel BeginLabel;
    private javax.swing.JTextField BeginVeld;
    private javax.swing.JButton BerekenButton;
    private javax.swing.JLabel BestandLabel;
    private javax.swing.JTextField BestandVeld;
    private javax.swing.JLabel BestandsNaamLabel;
    private javax.swing.JLabel BestandsNaamTekstLabel;
    private javax.swing.JButton BladerButton;
    private javax.swing.JTextField EindVeld;
    private javax.swing.JTextArea GegevensArea;
    private javax.swing.JLabel HeaderLabel;
    private javax.swing.JLabel InformatieLabel;
    private javax.swing.JLabel KoptekstLabel;
    private javax.swing.JLabel Label0;
    private javax.swing.JLabel Label100;
    private javax.swing.JButton OpenButton;
    private javax.swing.JLabel TotLabel;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
